// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03D-zx1Djz4w5UlifgKLmH3x2x4j_Qr8',
    appId: '1:177777241056:web:f4242633ead087bbf0d985',
    messagingSenderId: '177777241056',
    projectId: 'data-usage-cc554',
    authDomain: 'data-usage-cc554.firebaseapp.com',
    storageBucket: 'data-usage-cc554.firebasestorage.app',
    measurementId: 'G-THGZQJB1W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkFK1uZkhFOsm_rWVci_k0rAmT0foZPQ',
    appId: '1:177777241056:android:332442c78f008e69f0d985',
    messagingSenderId: '177777241056',
    projectId: 'data-usage-cc554',
    storageBucket: 'data-usage-cc554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJ0f21yYlVC8gjI-9UR5CKLa9WVCqZ00',
    appId: '1:177777241056:ios:5047babccc873182f0d985',
    messagingSenderId: '177777241056',
    projectId: 'data-usage-cc554',
    storageBucket: 'data-usage-cc554.firebasestorage.app',
    iosBundleId: 'com.example.v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJ0f21yYlVC8gjI-9UR5CKLa9WVCqZ00',
    appId: '1:177777241056:ios:5047babccc873182f0d985',
    messagingSenderId: '177777241056',
    projectId: 'data-usage-cc554',
    storageBucket: 'data-usage-cc554.firebasestorage.app',
    iosBundleId: 'com.example.v2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA03D-zx1Djz4w5UlifgKLmH3x2x4j_Qr8',
    appId: '1:177777241056:web:6175c3d4ad0a16a9f0d985',
    messagingSenderId: '177777241056',
    projectId: 'data-usage-cc554',
    authDomain: 'data-usage-cc554.firebaseapp.com',
    storageBucket: 'data-usage-cc554.firebasestorage.app',
    measurementId: 'G-FPEFL1ZCZT',
  );
}
